import { MigrationInterface, QueryRunner } from "typeorm";

export class PaymentsFlowRefactor1787230962994 implements MigrationInterface {
    name = 'PaymentsFlowRefactor1787230962994'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_qets_ets"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_price_providers_provider_enum" AS ENUM('stripe', 'paystack')`);
        await queryRunner.query(`CREATE TABLE "plan_price_providers" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "planPriceId" uuid NOT NULL, "provider" "public"."plan_price_providers_provider_enum" NOT NULL, "stripePriceId" character varying, "paystackPlanCode" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a0e50e03ff493e32fc60ec3802d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_910550ef41a0f34ada1b51cd73" ON "plan_price_providers" ("planPriceId", "provider") `);
        await queryRunner.query(`CREATE TYPE "public"."affiliate_payout_accounts_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`CREATE TABLE "affiliate_payout_accounts" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "affiliateId" uuid NOT NULL, "currency" "public"."affiliate_payout_accounts_currency_enum" NOT NULL, "bankName" character varying NOT NULL, "accountNumber" character varying NOT NULL, "accountName" character varying NOT NULL, "bankCode" character varying, "isDefault" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e231b305adbc7a8e2e6e3105af1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a89bcd3d2ff05a89d958d1733d" ON "affiliate_payout_accounts" ("affiliateId", "currency") `);
        await queryRunner.query(`CREATE INDEX "IDX_19740801c3295a171f021b1937" ON "affiliate_payout_accounts" ("affiliateId") `);
        await queryRunner.query(`ALTER TABLE "plan_prices" DROP COLUMN "stripePriceId"`);
        await queryRunner.query(`ALTER TABLE "plan_prices" DROP COLUMN "paystackPlanCode"`);
        await queryRunner.query(`ALTER TABLE "region_currencies" DROP COLUMN "paymentProvider"`);
        await queryRunner.query(`DROP TYPE "public"."region_currencies_paymentprovider_enum"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "affiliate_profiles" DROP COLUMN "totalPaidOut"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" ADD "payoutAccountId" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."affiliate_payouts_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" ADD "currency" "public"."affiliate_payouts_currency_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passages" ADD "contentFormat" character varying(20) NOT NULL DEFAULT 'markdown'`);
        await queryRunner.query(`ALTER TABLE "topics" ADD "contentFormat" character varying(20) NOT NULL DEFAULT 'markdown'`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "contentFormat" character varying(20) NOT NULL DEFAULT 'markdown'`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "discussions" json`);
        await queryRunner.query(`ALTER TYPE "public"."donations_currency_enum" RENAME TO "donations_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."donations_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" TYPE "public"."donations_currency_enum" USING "currency"::"text"::"public"."donations_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."donations_currency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."givebacks_currency_enum" RENAME TO "givebacks_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."givebacks_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" TYPE "public"."givebacks_currency_enum" USING "currency"::"text"::"public"."givebacks_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."givebacks_currency_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_216079c4298f848a15e49bd94b"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_prices_currency_enum" RENAME TO "plan_prices_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_prices_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "plan_prices" ALTER COLUMN "currency" TYPE "public"."plan_prices_currency_enum" USING "currency"::"text"::"public"."plan_prices_currency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."plan_prices_currency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."transactions_currency_enum" RENAME TO "transactions_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" TYPE "public"."transactions_currency_enum" USING "currency"::"text"::"public"."transactions_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."transactions_currency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."subscriptions_currency_enum" RENAME TO "subscriptions_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" TYPE "public"."subscriptions_currency_enum" USING "currency"::"text"::"public"."subscriptions_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_currency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."region_currencies_currency_enum" RENAME TO "region_currencies_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."region_currencies_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" TYPE "public"."region_currencies_currency_enum" USING "currency"::"text"::"public"."region_currencies_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" SET DEFAULT 'USD'`);
        await queryRunner.query(`DROP TYPE "public"."region_currencies_currency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."commissions_currency_enum" RENAME TO "commissions_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."commissions_currency_enum" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD', 'ZAR', 'KES', 'UGX', 'TZS', 'XOF', 'XAF')`);
        await queryRunner.query(`ALTER TABLE "commissions" ALTER COLUMN "currency" TYPE "public"."commissions_currency_enum" USING "currency"::"text"::"public"."commissions_currency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."commissions_currency_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_216079c4298f848a15e49bd94b" ON "plan_prices" ("planId", "currency") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3fd460802a6b5a4d93d2a2ca9" ON "commissions" ("affiliateId", "currency", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_01f2b8f755e79b7536a08d61e4" ON "commissions" ("affiliateId", "currency", "amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bbd56b5622ff6cbe64c17ff2c" ON "affiliate_payouts" ("affiliateId", "currency") `);
        await queryRunner.query(`ALTER TABLE "plan_price_providers" ADD CONSTRAINT "FK_6126d1098ad901e8197b7dabaf7" FOREIGN KEY ("planPriceId") REFERENCES "plan_prices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" ADD CONSTRAINT "FK_c6c30f7fd9a3c7ee1176e3323a8" FOREIGN KEY ("payoutAccountId") REFERENCES "affiliate_payout_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affiliate_payout_accounts" ADD CONSTRAINT "FK_19740801c3295a171f021b1937e" FOREIGN KEY ("affiliateId") REFERENCES "affiliate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "affiliate_payout_accounts" DROP CONSTRAINT "FK_19740801c3295a171f021b1937e"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" DROP CONSTRAINT "FK_c6c30f7fd9a3c7ee1176e3323a8"`);
        await queryRunner.query(`ALTER TABLE "plan_price_providers" DROP CONSTRAINT "FK_6126d1098ad901e8197b7dabaf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bbd56b5622ff6cbe64c17ff2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01f2b8f755e79b7536a08d61e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3fd460802a6b5a4d93d2a2ca9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_216079c4298f848a15e49bd94b"`);
        await queryRunner.query(`CREATE TYPE "public"."commissions_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "commissions" ALTER COLUMN "currency" TYPE "public"."commissions_currency_enum_old" USING "currency"::"text"::"public"."commissions_currency_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."commissions_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."commissions_currency_enum_old" RENAME TO "commissions_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."region_currencies_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" TYPE "public"."region_currencies_currency_enum_old" USING "currency"::"text"::"public"."region_currencies_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ALTER COLUMN "currency" SET DEFAULT 'USD'`);
        await queryRunner.query(`DROP TYPE "public"."region_currencies_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."region_currencies_currency_enum_old" RENAME TO "region_currencies_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" TYPE "public"."subscriptions_currency_enum_old" USING "currency"::"text"::"public"."subscriptions_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."subscriptions_currency_enum_old" RENAME TO "subscriptions_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" TYPE "public"."transactions_currency_enum_old" USING "currency"::"text"::"public"."transactions_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."transactions_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."transactions_currency_enum_old" RENAME TO "transactions_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_prices_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "plan_prices" ALTER COLUMN "currency" TYPE "public"."plan_prices_currency_enum_old" USING "currency"::"text"::"public"."plan_prices_currency_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."plan_prices_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_prices_currency_enum_old" RENAME TO "plan_prices_currency_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_216079c4298f848a15e49bd94b" ON "plan_prices" ("currency", "planId") `);
        await queryRunner.query(`CREATE TYPE "public"."givebacks_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" TYPE "public"."givebacks_currency_enum_old" USING "currency"::"text"::"public"."givebacks_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "givebacks" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."givebacks_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."givebacks_currency_enum_old" RENAME TO "givebacks_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."donations_currency_enum_old" AS ENUM('NGN', 'USD', 'GBP', 'EUR', 'CAD', 'AUD', 'GHS', 'GMD')`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" TYPE "public"."donations_currency_enum_old" USING "currency"::"text"::"public"."donations_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "donations" ALTER COLUMN "currency" SET DEFAULT 'NGN'`);
        await queryRunner.query(`DROP TYPE "public"."donations_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."donations_currency_enum_old" RENAME TO "donations_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "discussions"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "contentFormat"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP COLUMN "contentFormat"`);
        await queryRunner.query(`ALTER TABLE "passages" DROP COLUMN "contentFormat"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" DROP COLUMN "currency"`);
        await queryRunner.query(`DROP TYPE "public"."affiliate_payouts_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" DROP COLUMN "payoutAccountId"`);
        await queryRunner.query(`ALTER TABLE "affiliate_profiles" ADD "totalPaidOut" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" ADD "paymentMethod" character varying`);
        await queryRunner.query(`ALTER TABLE "affiliate_payouts" ADD "paymentDetails" json`);
        await queryRunner.query(`CREATE TYPE "public"."region_currencies_paymentprovider_enum" AS ENUM('stripe', 'paystack')`);
        await queryRunner.query(`ALTER TABLE "region_currencies" ADD "paymentProvider" "public"."region_currencies_paymentprovider_enum" NOT NULL DEFAULT 'stripe'`);
        await queryRunner.query(`ALTER TABLE "plan_prices" ADD "paystackPlanCode" character varying`);
        await queryRunner.query(`ALTER TABLE "plan_prices" ADD "stripePriceId" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19740801c3295a171f021b1937"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a89bcd3d2ff05a89d958d1733d"`);
        await queryRunner.query(`DROP TABLE "affiliate_payout_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."affiliate_payout_accounts_currency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_910550ef41a0f34ada1b51cd73"`);
        await queryRunner.query(`DROP TABLE "plan_price_providers"`);
        await queryRunner.query(`DROP TYPE "public"."plan_price_providers_provider_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_qets_ets" ON "question_exam_type_subjects" ("examTypeSubjectId") `);
    }

}
